name: kapil_sahu_cred
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  connectivity_plus: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.1.0
  flutter_modular: ^5.0.3
  flutter_svg: ^2.0.9
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  logger: ^1.3.0
  mockito: ^5.4.0
  modular_test: ^2.0.0
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^5.0.0
  test: ^1.21.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    # Vectors
    - assets/
    - assets/images/
    - assets/fonts/

    # Locales
    - i18n/en.json

    # Env files
    - development.env
    - mock.env
    - production.env

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
